# Change the label name in the job if needed.
# If the label is already present, this job runs successfully and does nothing.
name: Label new issues
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  label_issue:
    name: Add 'stats' label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['stats']
            })
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/tchapgouv/projects/8
          github-token: ${{ secrets.PROJECT_TOKEN }}
